### PR TITLE
Fixes + Add Random H Thats Valid

### PR DESCRIPTION
**Pull request by ptraced**
- Do ColorDepth Properly
- Make H Random and Valid

### CODE REVIEW

**Comment by VendorAttestation** [comment]
Note before anyone thinks this will work out the box some things still need to update sniff flow for FC after he pulls

This only fixes a telltale / bda randomization

**Comment by billispro** [comment]
test

**Comment by doctor82** [comment]
Doesnt it get access Denied and it still doesnt match headers and cookies

**Comment by VendorAttestation** [comment]
> Doesnt it get access Denied and it still doesnt match headers and cookies

this has nothing to do with the rest just BDA stuff i won't be helping with that 👯

**Pull request merged**
